[system]
name = "AI Agent Role-Playing System"
version = "0.1.0"
log_level = "INFO"
log_directory = "./logs"
transcripts_directory = "./transcripts"

[audio]
device_index = 5
sample_rate = 48000
channels = 2

[knowledge]
vector_db_path = "./data/chroma"
document_path = "./data/documents"