[system]
name = "AI Agent Role-Playing System"
version = "0.1.0"
log_level = "INFO"
log_directory = "./logs"

[audio]
device_index = "plughw:CARD=U5,DEV=0"  # Replace with your device's identifier
sample_rate = 48000
channels = 6